### ISSUE TITLE
ipykernal error on import in dev-py3

### ISSUE THREAD

**Issue by mrudula-gopalkrishna** [dannyjacobs/ECHO#12]
Throws ipykernel error on trying to import ECHO but everything seems to work just fine if import is run again. 

````
Usage: ipykernel_launcher.py [options]

ipykernel_launcher.py: error: no such option: -f

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
```

**Comment by dmlewis9** [comment]
Fixed in https://github.com/dannyjacobs/ECHO/commit/949001681af75a9d5bc064e34cf424b65a15aca8.
