### ISSUE TITLE
Need suite of tools to analyze beams from CST

### ISSUE THREAD

**Issue by mickeyhorn** [dannyjacobs/ECHO#19]
**Currently Have/Using:**
_CST_to_healpix.py_ script in this repo :: converts CST export file to healpix fits files
_Drone_CSTBeam_HealpixPlots_ jupyter notebook in Mickey's Dropbox workspace :: converts CST export file to mollviews, gridded views, and slices
_vivaldi_beam_compare_ jupyter notebook sent by Honggeun :: plots mollviews and does differencing between beams
_plot_slices.py_ script in this repo (old) :: makes slices from healpix fits files

**We Want:**
Mollviews
Gridded Views (maybe from top and bottom?)
Polar Cuts (with ability to tweak theta and phi viewing angles)
1D Slices (e-plane and h-plane)
Ability to difference beams and view all above plots
Plot both directivity and gain (ieee)

**Comment by dmlewis9** [comment]
all implemented except for beam differencing and directivity/gain plots

**Comment by dmlewis9** [comment]
Make a ReadTheDocs tutorial to explain beam manipulation and create plots.
