### ISSUE TITLE
plot_polar() function in observations.py 

### ISSUE THREAD

**Issue by mrudula-gopalkrishna** [dannyjacobs/ECHO#36]
plot_polar() currently seems to only works for altitude= 0.

Also not sure what this piece of code intended to do:  
`alt[:]=altitude*np.pi/2 `

**Comment by dmlewis9** [comment]
Hmmm, it seems to only work with certain altitudes. I'm working on figuring out a fix.

Also that line simply converts the decimal altitude into radians.

**Comment by dmlewis9** [comment]
Fixed in https://github.com/dannyjacobs/ECHO/commit/02512b286ee71829c630926877a34902e9d8b5e1, function should work properly now.
